### ISSUE TITLE
README.md 추가해주세요

### ISSUE THREAD

**Issue by HurSungYun** [hyungkee/jm_webserver_spring#1]
JaMong 이 어떤 프로젝트였나요?

**Comment by hyungkee** [comment]
JaMong은 빅데이터를 활용한 개인화 데이트코스 추천 서비스입니다. MySQL + Spring으로 진행중이며 Restful을 중간에 도입해 전환중입니다. 추천엔진은 비공개이며 현재 프로젝트 자체가 무기한 연기로 중단된 상태입니다.

**Comment by HurSungYun** [comment]
@hyungkee Thx a lot!
